# Simple workflow for deploying static content to GitHub Pages
name: Deploy
on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '22.6.0'
      - name: Install Dependencies
        run: npm ci
      - name: Save error log
        uses: actions/upload-artifact@v4.4.3
        if: ${{ failure() }}
        with:
          name: npm-debug-log-${{ hashFiles('package-lock.json') }}
          path: npm-debug.log
      - name: Build
        run: npm run build:deploy
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: './build/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
